---
- name: Check BusinessCentral is running
  command: >
    oc rollout status DeploymentConfig/rhpam-authoring-rhpamcentr --watch=true -n "{{ _namespace }}"

- name: Get Business Central route host
  command: >
    oc get route/rhpam-authoring-rhpamcentr -o jsonpath='{.spec.host}' -n "{{ _namespace }}"
  register: businesscentral_host
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: businesscentral_host.stdout != ""

- name: Wait for Business Central route to respond with 200
  uri:
    url: "https://{{ businesscentral_host.stdout }}"
    method: GET
    validate_certs: false
    follow_redirects: yes
  register: bizcentralresult
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentralresult.status == 200

- name: Check space exists in Business Central (note; error can be ignored)
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/spaces/workshop"
    method: GET
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
  register: bizcentralspace
  ignore_errors: true

- name: Create space in Business Central
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/spaces"
    method: POST
    body: "{{ body }}"
    body_format: json
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
    status_code: 202
  register: bizcentralclone
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentralclone.status == 202
  when: bizcentralspace.status == 404
  vars:
    body:
      name: "workshop"
      description: "Proactive Fraud Management with Case Management, Kafka and DMN Services"
      owner: "admin"
      defaultGroupId: "com.demo"

- name: Check project exists in Business Central (note; error can be ignored)
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/spaces/workshop/projects/proactive-fraud-detection-case"
    method: GET
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
  register: bizcentralproject
  ignore_errors: true

- name: Clone case into Business Central
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/spaces/workshop/git/clone"
    method: POST
    body: "{{ body }}"
    body_format: json
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
    status_code: 202
  register: bizcentralclone
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentralclone.status == 202
  when: bizcentralproject.status == 404
  vars:
    body:
      name: "proactive-fraud-detection-case"
      description: "proactive-fraud-detection-case"
      gitURL: "https://gitlab.com/garethahealy/proactive-fraud-detection-case.git"
      #gitURL: "http://mygitea.gitea.svc.cluster.local:3000/{{ _namespace }}/pam-fraudmanagement-case.git"

- name: Check job status for clone case in Business Central
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/jobs/{{ bizcentralclone.json.jobId }}"
    method: GET
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
  register: bizcentralclone_job
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentralclone_job.json.status == "SUCCESS"
  when: bizcentralproject.status == 404

- name: Maven install for project proactive-fraud-detection-case
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/spaces/workshop/projects/proactive-fraud-detection-case/maven/install"
    method: POST
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
    status_code: 202
  register: bizcentralinstall
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentralinstall.status == 202

- name: Check job status for maven install for project proactive-fraud-detection-case
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/jobs/{{ bizcentralinstall.json.jobId }}"
    method: GET
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
  register: bizcentralinstall_job
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentralinstall_job.json.status == "SUCCESS"

- name: Maven deploy for project proactive-fraud-detection-case
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/spaces/workshop/projects/proactive-fraud-detection-case/maven/deploy"
    method: POST
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
    status_code: 202
  register: bizcentraldeploy
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentraldeploy.status == 202

- name: Check job status for maven deplop for project proactive-fraud-detection-case
  uri:
    url: "https://{{ businesscentral_host.stdout }}/rest/jobs/{{ bizcentraldeploy.json.jobId }}"
    method: GET
    validate_certs: false
    follow_redirects: yes
    user: "{{ _namespace }}"
    password: "{{ _account_password }}"
    force_basic_auth: true
  register: bizcentraldeploy_job
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizcentraldeploy_job.json.status == "SUCCESS"