---
- name: Create operator
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/businessautomation/operator.yml' ) | from_yaml }}"

- name: Wait until csv/{{ _businessautomation_csv_version }} is Succeeded
  command: >
    oc get csv/{{ _businessautomation_csv_version }} -o jsonpath='{.status.phase}' -n "{{ _namespace }}"
  register: bizscsv
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: bizscsv.stdout == "Succeeded"

- name: Create Kie App
  k8s:
    state: present
    namespace: "{{ _namespace }}"
    definition: "{{ lookup('file', role_path ~ '/files/businessautomation/kie.yml' ) | from_yaml }}"

- name: Wait until KieApp has Deployed condition
  command: >
    oc get kieapp/rhpam-authoring -o jsonpath='{.status.conditions[?(@.type=="Deployed")].status}' -n "{{ _namespace }}"
  register: kieapp
  retries: "{{ _retry }}"
  delay: "{{ _delay }}"
  until: kieapp.stdout == "True"

- name: Check KieServer is running
  command: >
    oc rollout status DeploymentConfig/rhpam-authoring-kieserver --watch=true -n "{{ _namespace }}"

- name: Check BusinessCentral is running
  command: >
    oc rollout status DeploymentConfig/rhpam-authoring-rhpamcentr --watch=true -n "{{ _namespace }}"

- name: get business centranl url
  command: >
    oc get kieapp/rhpam-authoring  -o jsonpath='{.status.consoleHost}'
  register: businesscentral_host

- name: Clone pam project 1
  uri:
    url: "{{ businesscentral_host.stdout  }}/rest/spaces/MySpace/git/clone"
    method: POST
    return_content: yes
    headers:
      Content-Type: "application/json"
    body: '{"name": "proactive-fraud-detection-case", "description": "proactive-fraud-detection-case", "gitURL": "https://gitlab.com/ba-demos/proactive-fraud-detection/proactive-fraud-detection-case.git"}'
    body_format: json
    validate_certs: no
    status_code: 200,201,202,204
    user: "rhpamAdmin"
    password: "rhadminpassword123!"
    force_basic_auth: true
  register: clone_result

- debug: var=clone_result