apiVersion: app.kiegroup.org/v2
kind: KieApp
metadata:
  name: rhpam-authoring
spec:
  environment: rhpam-authoring
  objects:
    console:
      env:
        - name: KIE_ADMIN_USER
          value: "rhpamAdmin"
        - name: KIE_ADMIN_PWD
          value: "rhadminpassword123!"
